// Import libraries
import React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'

// Import components
import Header from '../components/Header'
import Breadcrumb from '../components/Breadcrumb'
import Footer from '../components/Footer'

// Import contexts
import { CartContext } from '../contexts/cart'

// Import utils
import { ICartItem } from '../utils/interfaces'

export default function Layout({ children }: any) {
  const currentUrl = useRouter().asPath

  const [totalPrice, setTotalPrice] = React.useState<number>(0)
  const [numberOfCartItem, setNumberOfCartItem] = React.useState<number>(0)
  const [cartItems, setCartItems] = React.useState<Array<ICartItem>>([])

  React.useEffect(() => {
    if (localStorage.getItem('douple-studio-cart') === null)
      localStorage.setItem('douple-studio-cart', JSON.stringify(cartItems))
  }, [])

  React.useEffect(() => {
    let cart: Array<ICartItem> = JSON.parse(localStorage.getItem('douple-studio-cart') || '[]')
    setCartItems(cart)
    setNumberOfCartItem(cart.reduce((prev, item) => (prev + item.quantity), 0))
    setTotalPrice(cart.reduce((prev, item) => (prev + Number(item.price) * item.quantity), 0))
  }, [])

  return (
    <>
      <Head>
        <title>Douple Studio</title>
        {/* <meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" type="image/png" href="https://firebasestorage.googleapis.com/v0/b/douple-studio.appspot.com/o/logo%2Flogo-icon_white.png?alt=media&token=5aa8e8ee-1d58-4b01-bfbf-8bbadc386e53" />
      </Head>
      <CartContext.Provider
        value={{
          totalPrice,
          setTotalPrice,
          numberOfCartItem,
          setNumberOfCartItem,
          cartItems,
          setCartItems
        }}
      >
        <Header />
        {currentUrl !== "/" && <Breadcrumb />}
        <main>{children}</main>
        <Footer />
      </CartContext.Provider>
    </>
  )
}