import Head from 'next/head'
import type { AppProps } from 'next/app'

// Import components
import Header from '../components/Header'
import Footer from '../components/Footer'

// Import styles
import '../styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Douple Studio</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </>
  )
}

export default MyApp
